seed: 42
device: 'cuda:0'

dir:
  root: '/media/dysk_a/jr_buler/RJG-gumed/RJG-6_labels_version'
  # clinical_data: '/media/dysk_a/jr_buler/RJG-gumed/crc_data_30-10-24.csv'
  clinical_data: '/media/dysk_a/jr_buler/RJG-gumed/crc_data_18-12-24.csv'
  inf: '/media/dysk_a/jr_buler/RJG-gumed/radiomics_info.pkl'
  pkl_radiomics: '/media/dysk_a/jr_buler/RJG-gumed/radiomics_features.pkl'


radiomics:  
  action: 'load' # 'extract' to extract radiomics, 'load' to load from pkl
  mode: 'parallel' #serial, parallel
  n_processes: 2 # for parallel mode only; if None, use [(all available) - 1] cores
  save: False # True, False; for action 'extract'
  
  multiple_binWidth: 
    if_multi: True # True, False; for action 'extract'; if True, extract radiomics for multiple bins
                   # if False, extract radiomics for single bin given in params.yml
    binWidths: [5, 25]  # a list of binWidths 
  
clinical_data_attributes: # selected most useful attributes from clinical data
  Nr pacjenta: int
  TNM wg mnie: str
  pT: str
  pN: str


  T: str
  N: str
  M 2: str
  M: str
<<<<<<< Updated upstream
  
=======
  TNM wg mnie: str
  Diagnoza: str
  # Zaznaczona Tk tłuszczoa 0-nie 1-tak 3-zaznaczona ale niezmieniona: str
  Zaznaczona Tk tłuszczoa 1-tak 2-zaznaczona ale niezmieniona: str
  # Zdrowe jelito lokalizacja: str
  # Liczba zaznaczonych ww chłonnych: str
>>>>>>> Stashed changes
  Liczba zaznaczonych ww chłonnych, 0- zaznaczone ale niepodejrzane: str
  liczba węzłów w preparacie: str
  liczba węzłów przerzutowych: str
  Zdrowe jelito lokalizacja: str
  Zaznaczona Tk tłuszczoa 1-tak 2-zaznaczona ale niezmieniona: str
  Diagnoza: str

  Płeć: str
  Wiek w momencie dx: int
  Masa ciała przed rozpoczęciu leczenia: str
  Wzrost: str
  BMI: float
  BMI kat: str

  Aspiryna (czy przyjmuje) tak/nie: str
  Palący: str
  # Paczkolata: float
  Cukrzyca (ta/nie): bool
  OSAS: bool
  Migotanie przedsionków (tak/nie): bool
  Choroba niedokrwienna serca (tak/nie): str
  Nadciśnienie tętnicze (tak/nie): str
  przebyty zawał (tak/nie): str
  przebyty udar (tak/nie): str
  stan po interwencji na naczyniach wieńcowych (tak/nie): str
  stan po pomostowaniu naczyń wieńcowych (tak/nie): str
  IBD: str
  Sterydy (czy przyjmuje) (tak/nie) (obecnie lub w ciagu ostatnich 3 miesięcy): str
  Immunosupresja (czy przyjmuje) (tak/nie) (obecnie lub w ciagu ostatnich 3 miesięcy): str